### ISSUE TITLE
backtrace runs twice when a function fails

### ISSUE THREAD

**Issue by Elsie19** [ab/bin#1]
#### File
```bash
#!/bin/bash
source ../base/backtrace.sh

function doomed_to_fail() {
    touch /root/test
}

doomed_to_fail
```

#### Output
```bash
touch: cannot touch '/root/test': Permission denied
Traceback (most recent call last):
  File "./test.sh", line 9, in main
    doomed_to_fail
  File "./test.sh", line 6, in doomed_to_fail
    touch /root/test
Exiting with status 1
Traceback (most recent call last):
  File "./test.sh", line 9, in main
    doomed_to_fail
Exiting with status 1
```

**Comment by ab** [comment]
A belated thanks for this report! It looks like when `-o errexit` is not set, bash will call the ERR trap once for each function / command that exits nonzero. This includes each function that exits nonzero as it unwinds the stack.

I played around with this a bit, but I couldn't figure out how to reliably suppress this without silencing other actual errors from the same function. (If the script continues, it could trigger other ERR traps from the same function if other commands exit nonzero.)

So for now I just documented that it's recommended to use `set -e` when using `bash-backtrace.sh`.
